#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP
 
web2="web-02"

if [ "$#" -eq 1 ]; then
	echo "The subdomain www is a A record and points to 54.210.47.110"
	echo "The subdomain lb-01 is a A record and points to 54.210.47.110"
	echo "The subdomain web-01 is a A record and points to 34.198.248.145"
	echo "The subdomain web-02 is a A record and points to 54.89.38.100"

elif [ "$#" -eq 2 ] && [ "$2" = "$web2" ]; then
	echo "The subdomain web-02 is a A record and points to 54.89.38.100"
fi
