#!/usr/bin/env bash
# Terminating SSL on HAproxy” means that HAproxy is configured to handle encrypted traffic, unencrypt it and pass it on to its destination

sudo apt update
sudo apt install certbot
sudo cerbot certonly --standalone -d www.itohan.tech
sudo crontab -e
