#!/usr/bin/env bash

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
	exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
