#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt update
sudo apt-get -y install nginx
sudo ss -tuln | grep ':80'

echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
