#!/usr/bin/env bash
# In this first task you need to configure web-02 to be identical

sudo apt update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTPS'
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/
echo "Hello World!" > /var/www/html/index.html

redirect_string='return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;'

#replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

#sudo sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-enabled/default

sudo sed -i "s|^.*\tlocation /redirect_me {.*$|location /redirect_me { '$redirect_string'}|" /etc/nginx/sites-enabled/default

sudo service nginx restart
