#!/usr/bin/env bash
# In this first task you need to configure web-02 to be identical to web-01

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTPS'
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/
echo "Hello World!" > /var/www/html/index.html

sudo sed -i "/server_name _;/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default

sudo service nginx restart
