#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu container’s

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTPS'

sudo service nginx restart
