#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th
count=0
until [ $count -eq 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
		echo "Best School"
	((count++))
done
