#!/usr/bin/env bash
# tjdnewlfiek

if ! [ -x  "$(command -v ufw)" ]; then
	sudo apt-get update
	sudo apt-get install -y ufw
fi
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw reload
