#!/usr/bin/env bash
# Firewalls can not only filter requests, they can also forward them

net="#net.ipv4.ip_forward=1"

sudo sed -i "s/$net/net.ipv4.ip_forward=1/" /etc/sysctl.conf
sudo sysctl -p
sudo service ufw restart
sudo ufw route allow proto tcp from any to any port 8080 redirect to port 80
