#!/usr/bin/env bash
# Firewalls can not only filter requests, they can also forward them

sudo sed -i ""
net="#net.ipv4.ip_forward=1"

sudo sed -i "s/$net/net.ipv4.ip_forward=1/" /etc/sysctl.conf
sudo sysctl -p
sudo service ufw restart
sudo service ufw enable
#sudo ufw route allow proto tcp from any to any port 8080 redirect to port 80
sudo sed -i '1i *nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT' /etc/ufw/before.rules
sudo ufw reload
