#!/usr/bin/env bash
# Run software as another user

#var="$(id -u "$1" &>/dev/null)"

if [ $# -ne 1 ]; then
	echo "USAGE: ./programname <username>"
	exit 1
fi
if id -u "$1" &>/dev/null; then
	echo "$1"
else
	echo "user does not exits"
fi
