#!/usr/bin/env bash
# Write a Bash script that configures the container to fit the above requirements

sudo adduser nginx
sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo service nginx restart
